<?php

return array(
    array(
        array(
            'id' => '1',
            'name' => 'book',
            'price' => '12.49',
            'import' => '0',
            'limited' => '1',
            'img' => 'no_image.png',
            'quantity' => '12',
        ),
        array(
            'id' => '2',
            'name' => 'music CD',
            'price' => '14.99',
            'import' => '0',
            'limited' => '0',
            'img' => 'no_image.png',
            'quantity' => '12',
        ),
        array(
            'id' => '3',
            'name' => 'chocolate bar',
            'price' => '0.85',
            'import' => '0',
            'limited' => '1',
            'img' => 'no_image.png',
            'quantity' => '12',
        ),
    ),
    array(
        array(
            'id' => '4',
            'name' => 'imported box of chocolates',
            'price' => '10.00',
            'import' => '1',
            'limited' => '1',
            'img' => 'no_image.png',
            'quantity' => '12',
        ),
        array(
            'id' => '5',
            'name' => 'imported bottle of perfume',
            'price' => '47.50',
            'import' => '1',
            'limited' => '0',
            'img' => 'no_image.png',
            'quantity' => '12',
        ),
    ),
    array(
        array(
            'id' => '6',
            'name' => 'imported bottle of perfume',
            'price' => '27.99',
            'import' => '1',
            'limited' => '0',
            'img' => 'no_image.png',
            'quantity' => '12',
        ),
        array(
            'id' => '7',
            'name' => 'bottle of perfume',
            'price' => '18.99',
            'import' => '0',
            'limited' => '0',
            'img' => 'no_image.png',
            'quantity' => '12',
        ),
        array(
            'id' => '8',
            'name' => 'packet of headache pills',
            'price' => '9.75',
            'import' => '0',
            'limited' => '1',
            'img' => 'no_image.png',
            'quantity' => '12',
        ),
        array(
            'id' => '9',
            'name' => 'box of imported chocolates',
            'price' => '11.25',
            'import' => '1',
            'limited' => '1',
            'img' => 'no_image.png',
            'quantity' => '12',
        ),
    ),
);
